import os
import sys
import subprocess
import re
from collections import Counter


# check that directory argument exists
if len(sys.argv) != 2:
    print("Usage: python script.py <directory>")
    sys.exit(1)
  

for entry in os.listdir(sys.argv[1]):
    full_path = os.path.join("/user","/adityarajsingh","csc344")
    subprocess.run(["wc", "-l", entry])
    identifiers = Counter()  
    first,last = entry.split(".")
    for line in entry:
        words = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b', entry)
        for word in words:
            # Further filter: if it's a known Python keyword, it's not an identifier to count
            # (You'd need a comprehensive list of keywords)
            if word not in ['if', 'else', 'for', 'while', 'def', 'class', 'return', 'True', 'False', 'None','Void']:
                identifiers[word] += 1
        
    with open(f"summary_{first}.html", "w") as file:
        

        html_content = """<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Summary """ + first + """</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Assignment 1 Summary</h1>
    <h2>It has --> """ + str(identifiers) + """

    <p>This is a test HTML file generated by Python.</p>

    <h2>Files</h2>
    <ul>
        <li><a href="file1.py">file1.py</a> — 10 lines</li>
        <li><a href="file2.py">file2.py</a> — 25 lines</li>
    </ul>

    <h2>Identifiers</h2>
    <ul>
        <li>main</li>
        <li>count_lines</li>
        <li>os</li>
        <li>sys</li>
    </ul>
</body>
</html>
"""
        file.write(html_content)
        file.close()

